### ISSUE TITLE
Cannot run a project on windows anymore

### ISSUE THREAD

**Issue by JulioBastidas** [foundation/foundation-sites#12036]
Hi i was working on a project normally using foundation watch on the cmd on windows but at the next day it just stopped working:

foundation-zurb-template@1.0.0 start E:\Uni\Cursos\cafeteria
gulp

[17:35:52] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command yarn upgrade
[17:35:54] Using gulpfile E:\Uni\Cursos\cafeteria\gulpfile.babel.js
[17:35:54] Starting 'default'...
[17:35:54] Starting 'build'...
[17:35:54] Starting 'clean'...
[17:35:54] Finished 'clean' after 2.82 ms
[17:35:54] Starting 'pages'...
[17:35:54] Starting 'javascript'...
[17:35:54] Starting 'images'...
[17:35:54] Starting 'copy'...
[17:35:54] 'images' errored after 185 ms
[17:35:54] TypeError: $.imagemin.jpegtran is not a function
at images (E:\Uni\Cursos\cafeteria/gulpfile.babel.js:144:18)
at bound (domain.js:402:14)
at runBound (domain.js:415:12)
at asyncRunner (E:\Uni\Cursos\cafeteria\node_modules\async-done\index.js:55:18)
at process._tickCallback (internal/process/next_tick.js:61:11)
[17:35:54] 'build' errored after 200 ms
[17:35:54] 'default' errored after 202 ms
[17:35:54] The following tasks did not complete: pages, javascript, copy
[17:35:54] Did you forget to signal async completion?
Error: foundation-zurb-template@1.0.0 start: gulp
Exit status 1
at EventEmitter. (C:\Program Files\node-v10.19.0-win-x64\node_modules\foundation-cli\node_modules\npm\lib\utils\lifecycle.js:217:16)
at EventEmitter.emit (events.js:198:13)
at ChildProcess. (C:\Program Files\node-v10.19.0-win-x64\node_modules\foundation-cli\node_modules\npm\lib\utils\spawn.js:24:14)
at ChildProcess.emit (events.js:198:13)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

i did not install something else and i did a system point recovery to install all again normally but now it seems like it stopped working.

npm version: 6.13..4

node version: 10.19.0

python 2.7.17

foundation CLI version 2.2.5

honestly the only thing i can think about is buy a new computer because i don't know where the problem is

**Comment by DanielRuf** [comment]
Hi @JulioBastidas,

> $.imagemin.jpegtran is not a function

Your jeptran binary is probably not compatible anymore with your platform. This can happen if some software changes (drivers, Windows version, build tools, ...).

Please try `npm rebuild --force` or `rm -rf node_modules && npm ci`.
Because it seems there is some issue with your jpegtran dependency which is a native binary.

In this case please check the output of `npm ci`. This is not an issue caused by foundation-sites.

**Comment by DanielRuf** [comment]
Hi @JulioBastidas,

> $.imagemin.jpegtran is not a function

Your jeptran binary is probably not compatible anymore with your platform. This can happen if some software changes (drivers, Windows version, build tools, Node version, ...).

Please try `npm rebuild --force` or `rm -rf node_modules && npm ci`.
Because it seems there is some issue with your jpegtran dependency which is a native binary.

In this case please check the output of `npm ci`. This is not an issue caused by foundation-sites.

**Comment by DanielRuf** [comment]
Also see https://github.com/sindresorhus/gulp-imagemin/issues/340 and check the content of your node_modules folder. Maybe you reinstalled / updated packages.

**Comment by JulioBastidas** [comment]
i checked the content and changed the code as described on issue #340 and it solved it, thank you very much.
