### ISSUE TITLE
Duplicate export 'Foundation'

### ISSUE THREAD

**Issue by GCheung55** [foundation/foundation-sites#12173]
## What should happen?
Rollup.js should be able to bundle without issue.

## What happens instead?
Rollup.js outputs an error "Duplicate export 'Foundation'".

## Possible Solution

`js/foundation.js` has 2 lines that export `Foundation`. Changing this should fix the bug.
...

## Test Case and/or Steps to Reproduce (for bugs)
This is the configuration I am using for rollup, pulled and slightly modified from [`ember-cli-foundation-6-sass`](https://github.com/acoustep/ember-cli-foundation-6-sass/blob/master/index.js#L78-L99):

```
{
    entry: 'node_modules/foundation-sites/js/foundation.js',
    format: 'es',
    dest: 'foundation-sites.js',
    plugins: [
        nodeResolve(),
        legacy({
        // In 6.4, foundation-sites/js/entries/plugins/foundation.core doesn't export anything, so we need to use legacy to export some things.
        'node_modules/foundation-sites/js/entries/plugins/foundation.core.js': {
            Foundation: 'window.Foundation',
            default: 'window.Foundation'
        },
        // 6.2.4 and 6.3.1
        'node_modules/foundation-sites/js/foundation.core.js': 'window.Foundation'
        })
    ],
    external: [
        'jquery'
    ]
}
```

## Context
I am unable to upgrade from 6.4.3 to a newer version, 6.5.0 and later.

## Your Environment
- Foundation version(s) used: 6.4.3, 6.5.0, 6.6.3
- Browser(s) name and version(s): N/A
- Device, Operating System and version: Macbook Pro, OSX 10.15.7
- Link to your project: N/A
- Node.js version: 10.22.1
- NPM version: 6.14.6
- Yarn version: 1.22.4
- Stack Trace and Error Report:

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Duplicate export 'Foundation'
    at error (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/rollup/dist/rollup.js:8007:2)
    at tryParse (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/rollup/dist/rollup.js:7710:10)
    at new Module (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/rollup/dist/rollup.js:7745:14)
    at /Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/rollup/dist/rollup.js:9495:17

  - code: [undefined]
  - codeFrame: Duplicate export 'Foundation'
  - errorMessage: Duplicate export 'Foundation'
        at Rollup
-~- created here: -~-
    at Rollup.Plugin (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/broccoli-rollup/node_modules/broccoli-plugin/index.js:7:31)
    at new Rollup (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/node_modules/broccoli-rollup/dist/index.js:74:72)
    at Class.treeForVendor (/Users/<redacted>/node_modules/ember-cli-foundation-6-sass/index.js:78:26)
```

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by GCheung55** [comment]
I'm going to investigate further and will file again if I can't figure it out.
