### ISSUE TITLE
M1 arm64 errors with npm install and foundation watch CLI command

### ISSUE THREAD

**Issue by alokjethanandani** [foundation/foundation-sites#12222]
## What should happen?

- The commands above should pull the dependencies and build the project 
- Attaching npm log files

## What happens instead?

- `foundation watch` does not build the project
- npm install fails with `node-gyp` and `node-sass `errors

[2021-04-08T20_51_46_101Z-debug.log](https://github.com/foundation/foundation-sites/files/6281840/2021-04-08T20_51_46_101Z-debug.log)
[2021-04-08T20_52_50_708Z-debug.log](https://github.com/foundation/foundation-sites/files/6281842/2021-04-08T20_52_50_708Z-debug.log)
[2021-04-08T20_57_52_850Z-debug.log](https://github.com/foundation/foundation-sites/files/6281843/2021-04-08T20_57_52_850Z-debug.log)
[2021-04-08T21_23_47_918Z-debug.log](https://github.com/foundation/foundation-sites/files/6281844/2021-04-08T21_23_47_918Z-debug.log)
[2021-04-08T21_27_50_420Z-debug.log](https://github.com/foundation/foundation-sites/files/6281845/2021-04-08T21_27_50_420Z-debug.log)
[2021-04-08T21_31_02_191Z-debug.log](https://github.com/foundation/foundation-sites/files/6281846/2021-04-08T21_31_02_191Z-debug.log)
[2021-04-08T21_33_04_745Z-debug.log](https://github.com/foundation/foundation-sites/files/6281847/2021-04-08T21_33_04_745Z-debug.log)
[2021-04-08T21_37_04_929Z-debug.log](https://github.com/foundation/foundation-sites/files/6281848/2021-04-08T21_37_04_929Z-debug.log)

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Install Node v15.14.0 using NVM 7.7.6 on an Apple M1 arm64 architecture
2. Use node version v15.14.0 using nvm
3. Run `npm install --global foundation-cli`
4. Clone https://github.com/alokjethanandani/mm3
5. Run command `foundation watch` - will fail and return the error shown below
6. Run command `npm install` - this will also return errors

**Error with command `foundation watch`**

```
foundation watch                                                                                      
fs.js:51
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:51:5
    at req_ (/Users/alok/.nvm/versions/node/v15.14.0/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/alok/.nvm/versions/node/v15.14.0/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/alok/.nvm/versions/node/v15.14.0/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
```

## Context
NPM version (npm -v): 7.7.6
Node version (node -v): v15.14.0
Node Process (node -p process.versions):
{
  node: '15.14.0',
  v8: '8.6.395.17-node.28',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k+quic',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
Node Platform (node -p process.platform): darwin
Node architecture (node -p process.arch): arm64
node-sass version (node -p "require('node-sass').info"):
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'node-sass'
Require stack:
- /Users/alok/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:131:12)
    at Object.runInThisContext (node:vm:308:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/alok/[eval]' ]
}

npm node-sass versions (npm ls node-sass):
alok@ /Users/alok
└── (empty)
I'm trying to build my personal website that uses Foundation for Sites 6 on an Apple M1 arm64 architecture.

Repo: https://github.com/alokjethanandani/mm3
Foundation for Sites 6: https://get.foundation/sites/docs/installation.html

I installed the foundation CLI using the command npm install foundation-cli --global. This process finished without any errors.

However, when I go to the directory that contains the website and try to build it using npm install I get the following errors:

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/alok/dev/mm3/node_modules/gulp-sass/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /Users/alok/.nvm/versions/node/v15.14.0/bin/node /Users/alok/dev/mm3/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
```

Attaching log files.

## Your Environment

- Foundation version(s) used: `Foundation for Sites 6`
- Browser(s) name and version(s): 
- Device, Operating System and version: Apple M1 arm64, Mac OS X BigSur 11.2.3
- Link to your project: [https://github.com/alokjethanandani/mm3](https://github.com/alokjethanandani/mm3)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please use the search next time before opening an issue which covers an issue that is already knwon and not directly caused by Foundation Sites itself but by a dependency.

https://github.com/foundation/foundation-sites/issues?q=is%3Aissue+sort%3Aupdated-desc+primordials+is+not+defined+is%3Aclosed

https://stackoverflow.com/search?q=primordials+is+not+defined

Please try to switch to Node 10 for this project using nvm, nodenv or n.

**Comment by DanielRuf** [comment]
> * `foundation watch` does not build the project
> 
> * npm install fails with `node-gyp` and `node-sass `errors

`watch` does nothing because the install step already fails (node-sass).

**Comment by DanielRuf** [comment]
Regarding `node-sass`, please try to upgrade it.

> 3369 error 5 warnings and 16 errors generated.

Also, please ask at https://github.com/sass/node-sass/issues regarding the `node-sass` problem, because this is a thirdparty dependency.

**Comment by DanielRuf** [comment]
Probably relevant and includes a few workarounds: https://github.com/sass/node-sass/issues/3033

**Comment by ursbraem** [comment]
@alokjethanandani were you able to solve your issue? I switched to an m1 and can't build legacy foundation projects (using node 10)
