### ISSUE TITLE
Foundation ZURB Template error - sassBuild error after running 'yarn start'

### ISSUE THREAD

**Issue by pnordboj** [foundation/foundation-sites#12448]
## What should happen?

... Should build the template and be viewable at localhost:8000

## What happens instead?

...[17:02:17] 'sassBuild' errored after 1.54 ms
[17:02:17] TypeError: The "listener" argument must be of type function. Received undefined
    at checkListener (node:events:259:3)
    at _addListener (node:events:560:3)
    at Transform.addListener (node:events:619:10)
    at Transform.on (node:internal/streams/readable:875:35)
    at sassBuild (/Users/%username%/Documents/GitHub/%folder%/projectname/gulpfile.babel.js:108:6)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (/Users/%username%/Documents/GitHub/%folder%/projectname/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[17:02:17] 'build' errored after 1.67 s
[17:02:17] 'default' errored after 1.67 s
error Command failed with exit code 1.

I changed gulp-sass from 4.1.1 to 5.1.0, if I have version 4.1.1 installed I get the following error:
error /Users/$username%/Documents/GitHub/%folder%/projectname/node_modules/gulp-sass/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/$username%/Documents/GitHub/%folder%/projectname/node_modules/gulp-sass/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/$username%/Documents/GitHub/%folder%/projectname/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. git clone https://github.com/foundation/foundation-zurb-template projectname
2 yarn
3 cd projectname
4 yarn start

## Context

...

## Your Environment

- Foundation version(s) used: 6.7.3
- Browser(s) name and version(s): 
- Device, Operating System and version: MacBook Pro M1, Monterey 12.4
- Link to your project: 

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by joeworkman** [comment]
Your order is a bit off... 

```
git clone https://github.com/foundation/foundation-zurb-template projectname
cd projectname
yarn install
yarn start
```

**Comment by L4rsS** [comment]
I have exactly same errors.
